import React from 'react';
import Head from 'next/head';

const About = () => {
  return (
    <div>
      <Head>
        <title>UBS | About</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      About
    </div>
  );
};

export default About;
